<x-layout>
    <x-blog-card></x-blog-card>
    <x-blog-card></x-blog-card>
    <x-blog-card></x-blog-card>
    <x-blog-card></x-blog-card>
    <x-blog-card></x-blog-card>
    <x-blog-card></x-blog-card>
    <x-blog-card></x-blog-card>
    <x-blog-card></x-blog-card>
    <x-blog-card></x-blog-card>
    <x-blog-card></x-blog-card>
    <x-blog-card></x-blog-card>
</x-layout>
